"""Add inventory and donor models with search capabilities

Revision ID: b71d0130b825
Revises: db6f5a0b75f7
Create Date: 2025-09-01 18:36:55.788688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71d0130b825'
down_revision = 'db6f5a0b75f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.create_index('idx_donor_batch', ['batch'], unique=False)
        batch_op.create_index('idx_donor_branch', ['branch'], unique=False)
        batch_op.create_index('idx_donor_email', ['email'], unique=False)
        batch_op.create_index('idx_donor_name', ['name'], unique=False)

    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('BOOK', 'LAPTOP', 'KIT', name='itemtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('authors', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('sku_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('date_of_donation', sa.Date(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_authors', ['authors'], unique=False)
        batch_op.create_index('idx_inventory_availability', ['available_quantity'], unique=False)
        batch_op.create_index('idx_inventory_created', ['created_at'], unique=False)
        batch_op.create_index('idx_inventory_department', ['department_id'], unique=False)
        batch_op.create_index('idx_inventory_dept_type', ['department_id', 'item_type'], unique=False)
        batch_op.create_index('idx_inventory_donor', ['donor_id'], unique=False)
        batch_op.create_index('idx_inventory_language', ['language'], unique=False)
        batch_op.create_index('idx_inventory_title', ['title'], unique=False)
        batch_op.create_index('idx_inventory_type', ['item_type'], unique=False)
        batch_op.create_index('idx_inventory_type_availability', ['item_type', 'available_quantity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_type_availability')
        batch_op.drop_index('idx_inventory_type')
        batch_op.drop_index('idx_inventory_title')
        batch_op.drop_index('idx_inventory_language')
        batch_op.drop_index('idx_inventory_donor')
        batch_op.drop_index('idx_inventory_dept_type')
        batch_op.drop_index('idx_inventory_department')
        batch_op.drop_index('idx_inventory_created')
        batch_op.drop_index('idx_inventory_availability')
        batch_op.drop_index('idx_inventory_authors')

    op.drop_table('inventory_item')
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_index('idx_donor_name')
        batch_op.drop_index('idx_donor_email')
        batch_op.drop_index('idx_donor_branch')
        batch_op.drop_index('idx_donor_batch')

    op.drop_table('donor')
    # ### end Alembic commands ###
