"""Initial migration with all models including waitlist

Revision ID: c8b55a5d59be
Revises: 
Create Date: 2025-09-05 22:33:26.723942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b55a5d59be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index('idx_department_active', ['is_active'], unique=False)
        batch_op.create_index('idx_department_code', ['code'], unique=False)
        batch_op.create_index('idx_department_name', ['name'], unique=False)

    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.create_index('idx_donor_batch', ['batch'], unique=False)
        batch_op.create_index('idx_donor_branch', ['branch'], unique=False)
        batch_op.create_index('idx_donor_email', ['email'], unique=False)
        batch_op.create_index('idx_donor_name', ['name'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('idx_role_level', ['level'], unique=False)
        batch_op.create_index('idx_role_name', ['name'], unique=False)

    op.create_table('transaction_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('transaction_counter', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_counter_date', ['date'], unique=False)

    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('BOOK', 'LAPTOP', 'KIT', name='itemtype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BORROWED', 'RESERVED', 'MAINTENANCE', 'LOST', 'DAMAGED', name='itemstatus'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('authors', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('sku_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('date_of_donation', sa.Date(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_authors', ['authors'], unique=False)
        batch_op.create_index('idx_inventory_availability', ['available_quantity'], unique=False)
        batch_op.create_index('idx_inventory_created', ['created_at'], unique=False)
        batch_op.create_index('idx_inventory_department', ['department_id'], unique=False)
        batch_op.create_index('idx_inventory_dept_type', ['department_id', 'item_type'], unique=False)
        batch_op.create_index('idx_inventory_donor', ['donor_id'], unique=False)
        batch_op.create_index('idx_inventory_language', ['language'], unique=False)
        batch_op.create_index('idx_inventory_title', ['title'], unique=False)
        batch_op.create_index('idx_inventory_type', ['item_type'], unique=False)
        batch_op.create_index('idx_inventory_type_availability', ['item_type', 'available_quantity'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('roll_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_department', ['department_id'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_roll_number', ['roll_number'], unique=False)
        batch_op.create_index('idx_user_status', ['status'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'REGISTER', 'PASSWORD_CHANGE', 'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_APPROVE', 'USER_SUSPEND', 'USER_ACTIVATE', 'ROLE_ASSIGN', 'ROLE_REMOVE', 'ROLE_CREATE', 'ROLE_UPDATE', 'INVENTORY_CREATE', 'INVENTORY_UPDATE', 'INVENTORY_DELETE', 'INVENTORY_VIEW', 'CHECKOUT_REQUEST', 'CHECKOUT_APPROVE', 'CHECKOUT_REJECT', 'RETURN_PROCESS', 'RENEWAL_REQUEST', 'RENEWAL_APPROVE', 'WAITLIST_JOIN', 'WAITLIST_LEAVE', 'WAITLIST_CLAIM', 'WAITLIST_NOTIFY', 'WAITLIST_EXPIRE', 'WAITLIST_CANCEL', 'FINE_CALCULATE', 'FINE_WAIVE', 'FINE_PAYMENT', 'SYSTEM_CONFIG', 'DATA_EXPORT', 'DATA_IMPORT', 'FAILED_LOGIN', 'UNAUTHORIZED_ACCESS', 'SUSPICIOUS_ACTIVITY', name='auditaction'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='auditseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_identifier', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_ip', ['ip_address'], unique=False)
        batch_op.create_index('idx_audit_severity', ['severity'], unique=False)
        batch_op.create_index('idx_audit_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'BORROWED', 'RETURNED', 'OVERDUE', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('renew_count', sa.Integer(), nullable=False),
    sa.Column('max_renewals', sa.Integer(), nullable=False),
    sa.Column('fine_accumulated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fine_waived', sa.Boolean(), nullable=False),
    sa.Column('fine_waived_by', sa.Integer(), nullable=True),
    sa.Column('fine_waived_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fine_waived_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_approver', ['approved_by_user_id'], unique=False)
        batch_op.create_index('idx_transaction_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('idx_transaction_item', ['item_id'], unique=False)
        batch_op.create_index('idx_transaction_item_status', ['item_id', 'status'], unique=False)
        batch_op.create_index('idx_transaction_requested', ['requested_at'], unique=False)
        batch_op.create_index('idx_transaction_status', ['status'], unique=False)
        batch_op.create_index('idx_transaction_status_due', ['status', 'due_date'], unique=False)
        batch_op.create_index('idx_transaction_user', ['user_id'], unique=False)
        batch_op.create_index('idx_transaction_user_status', ['user_id', 'status'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('waitlist_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NOTIFIED', 'EXPIRED', 'CLAIMED', 'CANCELLED', name='waitliststatus'), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='unique_user_item_waitlist')
    )
    with op.batch_alter_table('waitlist_request', schema=None) as batch_op:
        batch_op.create_index('idx_waitlist_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_waitlist_item_pos', ['item_id', 'position'], unique=False)
        batch_op.create_index('idx_waitlist_status', ['status'], unique=False)
        batch_op.create_index('idx_waitlist_user', ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TRANSACTION_APPROVED', 'TRANSACTION_REJECTED', 'TRANSACTION_ISSUED', 'TRANSACTION_RETURNED', 'TRANSACTION_OVERDUE', 'TRANSACTION_DUE_SOON', 'RENEWAL_APPROVED', 'RENEWAL_REJECTED', 'FINE_APPLIED', 'FINE_WAIVED', 'WAITLIST_AVAILABLE', 'SYSTEM_ANNOUNCEMENT', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_method', sa.String(length=50), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('idx_notification_created', ['created_at'], unique=False)
        batch_op.create_index('idx_notification_priority', ['priority'], unique=False)
        batch_op.create_index('idx_notification_transaction', ['transaction_id'], unique=False)
        batch_op.create_index('idx_notification_type', ['type'], unique=False)
        batch_op.create_index('idx_notification_unread', ['user_id', 'is_read'], unique=False)
        batch_op.create_index('idx_notification_user', ['user_id'], unique=False)
        batch_op.create_index('idx_notification_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_user_type', ['user_id', 'type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_user_type')
        batch_op.drop_index('idx_notification_user_created')
        batch_op.drop_index('idx_notification_user')
        batch_op.drop_index('idx_notification_unread')
        batch_op.drop_index('idx_notification_type')
        batch_op.drop_index('idx_notification_transaction')
        batch_op.drop_index('idx_notification_priority')
        batch_op.drop_index('idx_notification_created')

    op.drop_table('notification')
    with op.batch_alter_table('waitlist_request', schema=None) as batch_op:
        batch_op.drop_index('idx_waitlist_user')
        batch_op.drop_index('idx_waitlist_status')
        batch_op.drop_index('idx_waitlist_item_pos')
        batch_op.drop_index('idx_waitlist_expires')

    op.drop_table('waitlist_request')
    op.drop_table('user_roles')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('idx_transaction_user_status')
        batch_op.drop_index('idx_transaction_user')
        batch_op.drop_index('idx_transaction_status_due')
        batch_op.drop_index('idx_transaction_status')
        batch_op.drop_index('idx_transaction_requested')
        batch_op.drop_index('idx_transaction_item_status')
        batch_op.drop_index('idx_transaction_item')
        batch_op.drop_index('idx_transaction_id')
        batch_op.drop_index('idx_transaction_due_date')
        batch_op.drop_index('idx_transaction_approver')

    op.drop_table('transaction')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_target')
        batch_op.drop_index('idx_audit_severity')
        batch_op.drop_index('idx_audit_ip')
        batch_op.drop_index('idx_audit_created')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_status')
        batch_op.drop_index('idx_user_roll_number')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_department')

    op.drop_table('user')
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_type_availability')
        batch_op.drop_index('idx_inventory_type')
        batch_op.drop_index('idx_inventory_title')
        batch_op.drop_index('idx_inventory_language')
        batch_op.drop_index('idx_inventory_donor')
        batch_op.drop_index('idx_inventory_dept_type')
        batch_op.drop_index('idx_inventory_department')
        batch_op.drop_index('idx_inventory_created')
        batch_op.drop_index('idx_inventory_availability')
        batch_op.drop_index('idx_inventory_authors')

    op.drop_table('inventory_item')
    with op.batch_alter_table('transaction_counter', schema=None) as batch_op:
        batch_op.drop_index('idx_transaction_counter_date')

    op.drop_table('transaction_counter')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('idx_role_name')
        batch_op.drop_index('idx_role_level')

    op.drop_table('role')
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_index('idx_donor_name')
        batch_op.drop_index('idx_donor_email')
        batch_op.drop_index('idx_donor_branch')
        batch_op.drop_index('idx_donor_batch')

    op.drop_table('donor')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index('idx_department_name')
        batch_op.drop_index('idx_department_code')
        batch_op.drop_index('idx_department_active')

    op.drop_table('department')
    # ### end Alembic commands ###
