"""Add fine calculation and tracking models

Revision ID: e38cff5b2ccf
Revises: c8b55a5d59be
Create Date: 2025-09-05 22:36:31.697911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38cff5b2ccf'
down_revision = 'c8b55a5d59be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('book', 'laptop', 'kit', name='item_type_enum'), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('max_fine_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('escalation_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type')
    )
    with op.batch_alter_table('fine_configuration', schema=None) as batch_op:
        batch_op.create_index('idx_fine_config_active', ['is_active'], unique=False)
        batch_op.create_index('idx_fine_config_type', ['item_type'], unique=False)

    op.create_table('fine_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('fine_date', sa.Date(), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_waived', sa.Boolean(), nullable=False),
    sa.Column('waived_by', sa.Integer(), nullable=True),
    sa.Column('waived_reason', sa.Text(), nullable=True),
    sa.Column('waived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['waived_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fine_record', schema=None) as batch_op:
        batch_op.create_index('idx_fine_record_created', ['created_at'], unique=False)
        batch_op.create_index('idx_fine_record_date', ['fine_date'], unique=False)
        batch_op.create_index('idx_fine_record_transaction', ['transaction_id'], unique=False)
        batch_op.create_index('idx_fine_record_user', ['user_id'], unique=False)
        batch_op.create_index('idx_fine_record_waived', ['is_waived'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine_record', schema=None) as batch_op:
        batch_op.drop_index('idx_fine_record_waived')
        batch_op.drop_index('idx_fine_record_user')
        batch_op.drop_index('idx_fine_record_transaction')
        batch_op.drop_index('idx_fine_record_date')
        batch_op.drop_index('idx_fine_record_created')

    op.drop_table('fine_record')
    with op.batch_alter_table('fine_configuration', schema=None) as batch_op:
        batch_op.drop_index('idx_fine_config_type')
        batch_op.drop_index('idx_fine_config_active')

    op.drop_table('fine_configuration')
    # ### end Alembic commands ###
